// Generated by agent_team_v15.openapi_generator — patched for namespaced exports
export * from './types';

export interface RequestOptions {
  baseUrl?: string;
  init?: RequestInit;
}

export interface ApiError {
  code: number;
  message: string;
  details?: unknown;
}

export class ApiRequestError extends Error {
  public readonly status: number;
  public readonly body: { error: ApiError } | null;

  constructor(status: number, statusText: string, body: { error: ApiError } | null) {
    super(body?.error?.message ?? `API request failed: ${status} ${statusText}`);
    this.name = 'ApiRequestError';
    this.status = status;
    this.body = body;
  }
}

async function request<T>(
  method: string,
  path: string,
  args: { query?: Record<string, unknown>; body?: unknown } = {},
  options: RequestOptions = {},
): Promise<T> {
  const baseUrl = (options.baseUrl || '').replace(/\/$/, '');
  const url = new URL(
    baseUrl + path,
    typeof window !== 'undefined' ? window.location.origin : 'http://localhost',
  );
  if (args.query) {
    for (const [key, value] of Object.entries(args.query)) {
      if (value !== undefined && value !== null) {
        url.searchParams.set(key, String(value));
      }
    }
  }

  const headers: Record<string, string> = {};
  if (args.body !== undefined) {
    headers['Content-Type'] = 'application/json';
  }

  const response = await fetch(url.toString(), {
    method,
    headers,
    body: args.body !== undefined ? JSON.stringify(args.body) : undefined,
    ...(options.init || {}),
  });

  if (!response.ok) {
    let errorBody: { error: ApiError } | null = null;
    try {
      errorBody = await response.json();
    } catch {
      /* response had no JSON body */
    }
    throw new ApiRequestError(response.status, response.statusText, errorBody);
  }

  if (response.status === 204) {
    return undefined as T;
  }
  return (await response.json()) as T;
}

// ---------------------------------------------------------------------------
// Auth
// ---------------------------------------------------------------------------
import type { User } from './types';

export interface LoginResponse {
  data: { access_token: string; user: Omit<User, 'ownedProjects' | 'assignedTasks' | 'reportedTasks' | 'comments'> };
}
export interface RegisterResponse {
  data: { token: string; user: Omit<User, 'ownedProjects' | 'assignedTasks' | 'reportedTasks' | 'comments'> };
}
export interface MeResponse {
  data: Omit<User, 'ownedProjects' | 'assignedTasks' | 'reportedTasks' | 'comments'>;
}

export const auth = {
  login(
    args: { body: { email: string; password: string } },
    options: RequestOptions = {},
  ): Promise<LoginResponse> {
    return request<LoginResponse>('POST', '/auth/login', { body: args.body }, options);
  },

  register(
    args: { body: { email: string; name: string; password: string } },
    options: RequestOptions = {},
  ): Promise<RegisterResponse> {
    return request<RegisterResponse>('POST', '/auth/register', { body: args.body }, options);
  },

  me(options: RequestOptions = {}): Promise<MeResponse> {
    return request<MeResponse>('GET', '/auth/me', {}, options);
  },
};

// ---------------------------------------------------------------------------
// Health
// ---------------------------------------------------------------------------
export const health = {
  check(options: RequestOptions = {}): Promise<unknown> {
    return request<unknown>('GET', '/health', {}, options);
  },
};

// ---------------------------------------------------------------------------
// Projects
// ---------------------------------------------------------------------------
import type { Project, ProjectStatus } from './types';

export interface PaginatedMeta {
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface ProjectListResponse {
  data: Project[];
  meta: PaginatedMeta;
}
export interface ProjectResponse {
  data: Project & { taskSummary?: { todo: number; inProgress: number; inReview: number; done: number; total: number } };
}

export const projects = {
  findAll(
    args: { query?: { status?: ProjectStatus; page?: number; limit?: number } } = {},
    options: RequestOptions = {},
  ): Promise<ProjectListResponse> {
    return request<ProjectListResponse>('GET', '/projects', { query: args.query as Record<string, unknown> }, options);
  },

  create(
    args: { body: { name: string; description: string } },
    options: RequestOptions = {},
  ): Promise<ProjectResponse> {
    return request<ProjectResponse>('POST', '/projects', { body: args.body }, options);
  },

  findById(
    args: { id: string },
    options: RequestOptions = {},
  ): Promise<ProjectResponse> {
    return request<ProjectResponse>('GET', `/projects/${args.id}`, {}, options);
  },

  update(
    args: { id: string; body: { name?: string; description?: string; status?: ProjectStatus } },
    options: RequestOptions = {},
  ): Promise<ProjectResponse> {
    return request<ProjectResponse>('PATCH', `/projects/${args.id}`, { body: args.body }, options);
  },

  remove(
    args: { id: string },
    options: RequestOptions = {},
  ): Promise<void> {
    return request<void>('DELETE', `/projects/${args.id}`, {}, options);
  },
};

// ---------------------------------------------------------------------------
// Tasks
// ---------------------------------------------------------------------------
import type { Task, TaskStatus, TaskPriority } from './types';

export interface TaskListResponse {
  data: Task[];
  meta: PaginatedMeta;
}
export interface TaskResponse {
  data: Task;
}

export type SortBy = 'due_date' | 'priority' | 'created_at';
export type SortOrder = 'asc' | 'desc';

export const tasks = {
  findAllByProject(
    args: {
      projectId: string;
      query?: {
        status?: TaskStatus;
        priority?: TaskPriority;
        assigneeId?: string;
        sortBy?: SortBy;
        sortOrder?: SortOrder;
        page?: number;
        limit?: number;
      };
    },
    options: RequestOptions = {},
  ): Promise<TaskListResponse> {
    return request<TaskListResponse>(
      'GET',
      `/projects/${args.projectId}/tasks`,
      { query: args.query as Record<string, unknown> },
      options,
    );
  },

  create(
    args: {
      projectId: string;
      body: {
        title: string;
        description?: string;
        priority?: TaskPriority;
        dueDate?: string;
        assigneeId?: string;
      };
    },
    options: RequestOptions = {},
  ): Promise<TaskResponse> {
    return request<TaskResponse>(
      'POST',
      `/projects/${args.projectId}/tasks`,
      { body: args.body },
      options,
    );
  },

  findById(
    args: { id: string },
    options: RequestOptions = {},
  ): Promise<TaskResponse> {
    return request<TaskResponse>('GET', `/tasks/${args.id}`, {}, options);
  },

  update(
    args: {
      id: string;
      body: {
        title?: string;
        description?: string;
        priority?: TaskPriority;
        dueDate?: string;
        assigneeId?: string;
      };
    },
    options: RequestOptions = {},
  ): Promise<TaskResponse> {
    return request<TaskResponse>('PATCH', `/tasks/${args.id}`, { body: args.body }, options);
  },

  remove(
    args: { id: string },
    options: RequestOptions = {},
  ): Promise<void> {
    return request<void>('DELETE', `/tasks/${args.id}`, {}, options);
  },

  transitionStatus(
    args: { id: string; body: { status: TaskStatus } },
    options: RequestOptions = {},
  ): Promise<TaskResponse> {
    return request<TaskResponse>('PATCH', `/tasks/${args.id}/status`, { body: args.body }, options);
  },
};

// ---------------------------------------------------------------------------
// Comments
// ---------------------------------------------------------------------------
import type { Comment } from './types';

export interface CommentListResponse {
  data: Comment[];
  meta: PaginatedMeta;
}
export interface CommentResponse {
  data: Comment;
}

export const comments = {
  findAll(
    args: { taskId: string; query?: { page?: number; limit?: number } },
    options: RequestOptions = {},
  ): Promise<CommentListResponse> {
    return request<CommentListResponse>(
      'GET',
      `/tasks/${args.taskId}/comments`,
      { query: args.query as Record<string, unknown> },
      options,
    );
  },

  create(
    args: { taskId: string; body: { content: string } },
    options: RequestOptions = {},
  ): Promise<CommentResponse> {
    return request<CommentResponse>(
      'POST',
      `/tasks/${args.taskId}/comments`,
      { body: args.body },
      options,
    );
  },
};
