// Generated by agent_team_v15.openapi_generator

export interface Comment {
  id: string;
  content: string;
  taskId: string;
  authorId: string;
  createdAt: string;
  task: Task;
  author: User;
}

export interface Project {
  id: string;
  name: string;
  description?: string;
  status: ProjectStatus;
  ownerId: string;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string;
  owner: User;
  tasks: Task[];
}

export type ProjectStatus = "ACTIVE" | "ARCHIVED";

export type Role = "ADMIN" | "MEMBER";

export interface Task {
  id: string;
  title: string;
  description?: string;
  status: TaskStatus;
  priority: TaskPriority;
  dueDate?: string;
  projectId: string;
  assigneeId?: string;
  reporterId: string;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string;
  project: Project;
  assignee?: User;
  reporter: User;
  comments: Comment[];
}

export type TaskPriority = "LOW" | "MEDIUM" | "HIGH" | "URGENT";

export type TaskStatus = "TODO" | "IN_PROGRESS" | "IN_REVIEW" | "DONE";

export interface User {
  id: string;
  email: string;
  name: string;
  role: Role;
  avatarUrl?: string;
  createdAt: string;
  updatedAt: string;
  ownedProjects: Project[];
  assignedTasks: Task[];
  reportedTasks: Task[];
  comments: Comment[];
}

export type sortBy = "due_date" | "priority" | "created_at";

export type sortOrder = "asc" | "desc";

