// Generated by agent_team_v15.openapi_generator
export * from './types';

export interface RequestOptions {
  baseUrl?: string;
  init?: RequestInit;
}

async function request<T>(
  method: string,
  path: string,
  args: { query?: Record<string, unknown>; body?: unknown } = {},
  options: RequestOptions = {},
): Promise<T> {
  const baseUrl = (options.baseUrl || '').replace(/\/$/, '');
  const url = new URL(baseUrl + path, typeof window !== 'undefined' ? window.location.origin : 'http://localhost');
  if (args.query) {
    for (const [key, value] of Object.entries(args.query)) {
      if (value !== undefined && value !== null) {
        url.searchParams.set(key, String(value));
      }
    }
  }
  const response = await fetch(url.toString(), {
    method,
    headers: args.body !== undefined ? { 'Content-Type': 'application/json' } : undefined,
    body: args.body !== undefined ? JSON.stringify(args.body) : undefined,
    ...(options.init || {}),
  });
  if (!response.ok) {
    throw new Error(`API request failed: ${response.status} ${response.statusText}`);
  }
  if (response.status === 204) {
    return undefined as T;
  }
  return (await response.json()) as T;
}

export async function getHello(
  args: {
},
  options: RequestOptions = {},
): Promise<string> {
  return request<string>(
    'GET',
    "/",
    {
    },
    options,
  );
}

export async function findAll(
  args: {
},
  options: RequestOptions = {},
): Promise<unknown> {
  return request<unknown>(
    'GET',
    "/<%= dasherize(name) %>",
    {
    },
    options,
  );
}

export async function create(
  args: {
  body?: unknown;
},
  options: RequestOptions = {},
): Promise<unknown> {
  return request<unknown>(
    'POST',
    "/<%= dasherize(name) %>",
    {
      body: args.body,
    },
    options,
  );
}

export async function findOne(
  args: {
  id: string;
},
  options: RequestOptions = {},
): Promise<unknown> {
  return request<unknown>(
    'GET',
    `/<%= dasherize(name) %>/${args.id}`,
    {
    },
    options,
  );
}

export async function update(
  args: {
  id: string;
  body?: unknown;
},
  options: RequestOptions = {},
): Promise<unknown> {
  return request<unknown>(
    'PATCH',
    `/<%= dasherize(name) %>/${args.id}`,
    {
      body: args.body,
    },
    options,
  );
}

export async function remove(
  args: {
  id: string;
},
  options: RequestOptions = {},
): Promise<void> {
  return request<void>(
    'DELETE',
    `/<%= dasherize(name) %>/${args.id}`,
    {
    },
    options,
  );
}

export async function login(
  args: {
  body?: unknown;
},
  options: RequestOptions = {},
): Promise<unknown> {
  return request<unknown>(
    'POST',
    "/api/auth/login",
    {
      body: args.body,
    },
    options,
  );
}

export async function me(
  args: {
  body?: unknown;
},
  options: RequestOptions = {},
): Promise<{ id: string; content: string; task_id: string; author_id: string; author: UserSummaryDto; created_at: string }> {
  return request<{ id: string; content: string; task_id: string; author_id: string; author: UserSummaryDto; created_at: string }>(
    'GET',
    "/api/auth/me",
    {
      body: args.body,
    },
    options,
  );
}

export async function register(
  args: {
  body?: unknown;
},
  options: RequestOptions = {},
): Promise<unknown> {
  return request<unknown>(
    'POST',
    "/api/auth/register",
    {
      body: args.body,
    },
    options,
  );
}

export async function findAll(
  args: {
  query?: {
    status?: string | number | boolean;
  };
},
  options: RequestOptions = {},
): Promise<unknown> {
  return request<unknown>(
    'GET',
    "/api/projects",
    {
      query: args.query,
    },
    options,
  );
}

export async function create(
  args: {
  body?: unknown;
},
  options: RequestOptions = {},
): Promise<unknown> {
  return request<unknown>(
    'POST',
    "/api/projects",
    {
      body: args.body,
    },
    options,
  );
}

export async function findOne(
  args: {
  id: string;
},
  options: RequestOptions = {},
): Promise<unknown> {
  return request<unknown>(
    'GET',
    `/api/projects/${args.id}`,
    {
    },
    options,
  );
}

export async function update(
  args: {
  id: string;
  body?: unknown;
},
  options: RequestOptions = {},
): Promise<unknown> {
  return request<unknown>(
    'PATCH',
    `/api/projects/${args.id}`,
    {
      body: args.body,
    },
    options,
  );
}

export async function remove(
  args: {
  id: string;
},
  options: RequestOptions = {},
): Promise<void> {
  return request<void>(
    'DELETE',
    `/api/projects/${args.id}`,
    {
    },
    options,
  );
}

export async function findAllByProject(
  args: {
  projectId: string;
  query?: {
    status?: string | number | boolean;
    priority?: string | number | boolean;
    assignee_id?: string | number | boolean;
    sort?: string | number | boolean;
    order?: string | number | boolean;
  };
},
  options: RequestOptions = {},
): Promise<unknown> {
  return request<unknown>(
    'GET',
    `/api/projects/${args.projectId}/tasks`,
    {
      query: args.query,
    },
    options,
  );
}

export async function create(
  args: {
  projectId: string;
  body?: unknown;
},
  options: RequestOptions = {},
): Promise<unknown> {
  return request<unknown>(
    'POST',
    `/api/projects/${args.projectId}/tasks`,
    {
      body: args.body,
    },
    options,
  );
}

export async function findOne(
  args: {
  id: string;
},
  options: RequestOptions = {},
): Promise<unknown> {
  return request<unknown>(
    'GET',
    `/api/tasks/${args.id}`,
    {
    },
    options,
  );
}

export async function update(
  args: {
  id: string;
  body?: unknown;
},
  options: RequestOptions = {},
): Promise<unknown> {
  return request<unknown>(
    'PATCH',
    `/api/tasks/${args.id}`,
    {
      body: args.body,
    },
    options,
  );
}

export async function remove(
  args: {
  id: string;
},
  options: RequestOptions = {},
): Promise<void> {
  return request<void>(
    'DELETE',
    `/api/tasks/${args.id}`,
    {
    },
    options,
  );
}

export async function transitionStatus(
  args: {
  id: string;
  body?: unknown;
},
  options: RequestOptions = {},
): Promise<unknown> {
  return request<unknown>(
    'PATCH',
    `/api/tasks/${args.id}/status`,
    {
      body: args.body,
    },
    options,
  );
}

export async function findAll(
  args: {
  taskId: string;
  query?: {
    page?: string | number | boolean;
    limit?: string | number | boolean;
  };
},
  options: RequestOptions = {},
): Promise<unknown> {
  return request<unknown>(
    'GET',
    `/api/tasks/${args.taskId}/comments`,
    {
      query: args.query,
    },
    options,
  );
}

export async function create(
  args: {
  taskId: string;
  body?: unknown;
},
  options: RequestOptions = {},
): Promise<unknown> {
  return request<unknown>(
    'POST',
    `/api/tasks/${args.taskId}/comments`,
    {
      body: args.body,
    },
    options,
  );
}

export async function findAll(
  args: {
  query?: {
    page?: string | number | boolean;
    limit?: string | number | boolean;
  };
},
  options: RequestOptions = {},
): Promise<unknown> {
  return request<unknown>(
    'GET',
    "/api/users",
    {
      query: args.query,
    },
    options,
  );
}

export async function findOne(
  args: {
  id: string;
},
  options: RequestOptions = {},
): Promise<unknown> {
  return request<unknown>(
    'GET',
    `/api/users/${args.id}`,
    {
    },
    options,
  );
}

export async function login(
  args: {
  body?: unknown;
},
  options: RequestOptions = {},
): Promise<unknown> {
  return request<unknown>(
    'POST',
    "/auth/login",
    {
      body: args.body,
    },
    options,
  );
}

export async function me(
  args: {
  body?: unknown;
},
  options: RequestOptions = {},
): Promise<{ id: string; content: string; task_id: string; author_id: string; author: UserSummaryDto; created_at: string }> {
  return request<{ id: string; content: string; task_id: string; author_id: string; author: UserSummaryDto; created_at: string }>(
    'GET',
    "/auth/me",
    {
      body: args.body,
    },
    options,
  );
}

export async function register(
  args: {
  body?: unknown;
},
  options: RequestOptions = {},
): Promise<unknown> {
  return request<unknown>(
    'POST',
    "/auth/register",
    {
      body: args.body,
    },
    options,
  );
}

export async function check(
  args: {
},
  options: RequestOptions = {},
): Promise<unknown> {
  return request<unknown>(
    'GET',
    "/health",
    {
    },
    options,
  );
}

export async function findAll(
  args: {
  query?: {
    status?: string | number | boolean;
  };
},
  options: RequestOptions = {},
): Promise<unknown> {
  return request<unknown>(
    'GET',
    "/projects",
    {
      query: args.query,
    },
    options,
  );
}

export async function create(
  args: {
  body?: unknown;
},
  options: RequestOptions = {},
): Promise<unknown> {
  return request<unknown>(
    'POST',
    "/projects",
    {
      body: args.body,
    },
    options,
  );
}

export async function findOne(
  args: {
  id: string;
},
  options: RequestOptions = {},
): Promise<unknown> {
  return request<unknown>(
    'GET',
    `/projects/${args.id}`,
    {
    },
    options,
  );
}

export async function update(
  args: {
  id: string;
  body?: unknown;
},
  options: RequestOptions = {},
): Promise<unknown> {
  return request<unknown>(
    'PATCH',
    `/projects/${args.id}`,
    {
      body: args.body,
    },
    options,
  );
}

export async function remove(
  args: {
  id: string;
},
  options: RequestOptions = {},
): Promise<void> {
  return request<void>(
    'DELETE',
    `/projects/${args.id}`,
    {
    },
    options,
  );
}

export async function findAllByProject(
  args: {
  projectId: string;
  query?: {
    status?: string | number | boolean;
    priority?: string | number | boolean;
    assignee_id?: string | number | boolean;
    sort?: string | number | boolean;
    order?: string | number | boolean;
  };
},
  options: RequestOptions = {},
): Promise<unknown> {
  return request<unknown>(
    'GET',
    `/projects/${args.projectId}/tasks`,
    {
      query: args.query,
    },
    options,
  );
}

export async function create(
  args: {
  projectId: string;
  body?: unknown;
},
  options: RequestOptions = {},
): Promise<unknown> {
  return request<unknown>(
    'POST',
    `/projects/${args.projectId}/tasks`,
    {
      body: args.body,
    },
    options,
  );
}

export async function findOne(
  args: {
  id: string;
},
  options: RequestOptions = {},
): Promise<unknown> {
  return request<unknown>(
    'GET',
    `/tasks/${args.id}`,
    {
    },
    options,
  );
}

export async function update(
  args: {
  id: string;
  body?: unknown;
},
  options: RequestOptions = {},
): Promise<unknown> {
  return request<unknown>(
    'PATCH',
    `/tasks/${args.id}`,
    {
      body: args.body,
    },
    options,
  );
}

export async function remove(
  args: {
  id: string;
},
  options: RequestOptions = {},
): Promise<void> {
  return request<void>(
    'DELETE',
    `/tasks/${args.id}`,
    {
    },
    options,
  );
}

export async function transitionStatus(
  args: {
  id: string;
  body?: unknown;
},
  options: RequestOptions = {},
): Promise<unknown> {
  return request<unknown>(
    'PATCH',
    `/tasks/${args.id}/status`,
    {
      body: args.body,
    },
    options,
  );
}

export async function findAll(
  args: {
  taskId: string;
},
  options: RequestOptions = {},
): Promise<unknown> {
  return request<unknown>(
    'GET',
    `/tasks/${args.taskId}/comments`,
    {
    },
    options,
  );
}

export async function create(
  args: {
  taskId: string;
  body?: unknown;
},
  options: RequestOptions = {},
): Promise<unknown> {
  return request<unknown>(
    'POST',
    `/tasks/${args.taskId}/comments`,
    {
      body: args.body,
    },
    options,
  );
}

export async function findAll(
  args: {
},
  options: RequestOptions = {},
): Promise<unknown> {
  return request<unknown>(
    'GET',
    "/users",
    {
    },
    options,
  );
}

export async function findOne(
  args: {
  id: string;
},
  options: RequestOptions = {},
): Promise<unknown> {
  return request<unknown>(
    'GET',
    `/users/${args.id}`,
    {
    },
    options,
  );
}

