// Generated by agent_team_v15.openapi_generator

export type QueryValue = string | number | boolean | null | undefined;

export interface Comment {
  id: string;
  content: string;
  task_id: string;
  author_id: string;
  created_at: string;
  task: Task;
  author: User;
}

export interface Project {
  id: string;
  name: string;
  description?: string;
  status: ProjectStatus;
  owner_id: string;
  deleted_at?: string;
  updated_at: string;
  owner: User;
  tasks: Task[];
}

export type ProjectStatus = "ACTIVE" | "ARCHIVED";

export type ProjectStatusEnum = "ACTIVE" | "ARCHIVED";

export type ProjectStatusFilter = "ACTIVE" | "ARCHIVED";

export interface Task {
  id: string;
  title: string;
  description?: string;
  status: TaskStatus;
  priority: TaskPriority;
  due_date?: string;
  project_id: string;
  assignee_id?: string;
  reporter_id: string;
  deleted_at?: string;
  updated_at: string;
  project: Project;
  assignee?: User;
  reporter: User;
  comments: Comment[];
}

export type TaskPriority = "LOW" | "MEDIUM" | "HIGH" | "URGENT";

export type TaskPriorityEnum = "LOW" | "MEDIUM" | "HIGH" | "URGENT";

export type TaskPriorityFilter = "LOW" | "MEDIUM" | "HIGH" | "URGENT";

export type TaskStatus = "TODO" | "IN_PROGRESS" | "IN_REVIEW" | "DONE";

export type TaskStatusEnum = "TODO" | "IN_PROGRESS" | "IN_REVIEW" | "DONE";

export type TaskStatusFilter = "TODO" | "IN_PROGRESS" | "IN_REVIEW" | "DONE";

export interface User {
  id: string;
  email: string;
  name: string;
  avatar_url?: string;
  created_at: string;
  updated_at: string;
  projects: Project[];
  assigned_tasks: Task[];
  reported_tasks: Task[];
  comments: Comment[];
}

export type UserRole = "ADMIN" | "MEMBER";

export type order = "asc" | "desc";

export type sort = "due_date" | "priority" | "created_at";

export type sort_by = "due_date" | "priority" | "created_at";

export type sort_order = "asc" | "desc";

